name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          platforms: linux/amd64, linux/arm64
          push: true
          file: ./Containerfile
          tags: | 
            ${{ vars.DOCKERHUB_USERNAME }}/ilo4:${{ github.ref_name }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/ilo4:latest
          
